name: idf
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - pip=22.0.4
  - jupyter=1.0.0
  - pandas=1.4.1
  - geopandas=0.10.2
  - xarray=2022.3.0
  - black-jupyter=22.3.0
  - isort=5.10.1
  - typer=0.4.1
  - pip:
      - idf-analysis==0.1.12
